print("Analizando datos")
print("Python es fantástico")
print("Añadida una nueva funcionalidad")
print("Calculando estadísticas...")
print("Estoy trabajando en la rama nueva-funcion")
print("Proyecto publicado en GitHub")